project:
  type: website
  output-dir: docs
website:
  title: MATHEMEDICIAN
  #site-url: https://cvoller.co.uk
  description: Blog
  #repo-url: https://github.com/cgvoller/cvoller.co.uk
  navbar:
    right:
    - text: About 
      href: about.qmd
    - text: "Misc"
      file: misc.qmd
    - icon: github
      href: https://github.com/cgvoller/
    - icon: linkedin
      href: https://www.linkedin.com/in/corey-v-027bb0198
format:
  html:
    mermaid:
      theme: dark
    #code-block-bg: true
    #code-block-border-left: "#000000"
    #code-block-border-left: true
    highlight-style: nord
    theme: slate
    css:
    - styles.css
    - include/webex.css
    smooth-scroll: true
    include-after-body: include/webex.js
editor: visual
