project:
  type: website
  output-dir: docs

website:
  title: "Mathemedician"
  navbar:
    right:
      - about.qmd
      - misc.qmd
      - icon: github
        href: https://github.com/cgvoller/
      - icon: linkedin
        href: https://www.linkedin.com/in/corey-v-027bb0198
format:
  html:
    theme: lux
    css: styles.css

editor: visual

